version: '3.8'

services:
  sbominsight:
    build:
      context: .  # Use the current directory as the context
      dockerfile: Dockerfile
    volumes:
      - sbom-output:/output
    entrypoint: ["/bin/sh", "-c", "./sbominsight -i alpine:latest -o json > /output/sbom.json && chmod 644 /output/sbom.json"]

  jsoncrack:
    image: sangam14/jsoncrack
    ports:
      - "8080:8080"
    volumes:
      - sbom-output:/app/public/json

volumes:
  sbom-output:
    driver: local
